project:
  type: website
  output-dir: docs

website:
  title: "Anthony Rozario"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - posts.qmd 
    
  page-footer:
    background: dark
    right: This website was inspired and adapted from [Sam Shanny-Csik](@https://samanthacsik.github.io/)

format:
  html:
    theme: 
      - flatly
      - styles.scss
    css: styles.css
    mainfont: Roboto Mono
    toc: true
    page-layout: full

editor: visual

