project:
  type: website
  output-dir: docs

website:
  title: "AnthonyRozario"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - posts.qmd 
    
  page-footer:
    background: dark
    right: This website was inspired and adapted from [Sam Shanny-Csik](https://samanthacsik.github.io/)

format:
  html:
    theme: 
      - flatly
      - styles.scss
    css: styles.css
    mainfont: Domine
    toc: true
    page-layout: full

editor: visual

