project:
  type: website

website:
  site-url: "https://anthonyrozario.com"
  title: "AnthonyRozario"
  description: "Portfolio showcasing projects & more!"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
  page-footer:
    background: dark
    right: This website was inspired and adapted from [Sam Shanny-Csik](https://samanthacsik.github.io/)

format:
  html:
    theme: 
      - flatly
      - styles.scss
    css: styles.css
    sansfont: Garamond
    mainfont: Domine
    toc: true
    page-layout: full
    includes:
      in-header: _includes/head.html

editor: visual
