project:
  type: website
  output-dir: docs

website:
  site-url: "https://anthonyrozario.com"
  title: "AnthonyRozario"
  description: "Portfolio showcasing projects & more!"
  navbar:
    title: false # override printing your website `title`
    logo: images/re1.png
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
  page-footer:
    background: dark
    right: This website was made with Quarto and inspired by [Sam Shanny-Csik](https://samanthacsik.github.io/)

format:
  html:
    theme: 
      - flatly
      - styles.scss
    css: styles.css
    sansfont: Garamond
    mainfont: Domine
    toc: true
    page-layout: full

editor: visual
