{
  "hash": "52339a08e15ea2c6622776e9073a2b0e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Physiological Factors of Obstructive Sleep Apnoea Severity\"\ndescription: \"A Multiple Regression Analysis of Arousal Index and Associated Risk Factors\"\nauthor:\n  - name: \"K. Anthony Rozario\"\n    affiliation: \"Academic, Macquarie University\"\ndate: 2025-05-21\nimage: preview-sleep.jpg\ncategories: [Academic]\ntags: [Quarto, R]\n\nformat:\n  html:\n    embed-resources: true\n      \n    toc: true\n    toc-depth: 4\n    toc-location: left\n    number-sections: true\n    number-depth: 4\n    title-block-banner: true\n\nexecute: \n  echo: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## Abstract\n\nThis study investigates key physiological risk factors associated with the severity of obstructive sleep apnoea (OSA). Using multiple linear regression, we analyze the relationship between the arousal index (ai), a measure of sleep disruption, and several predictors: `age`, body mass index (`BMI`), `neck size`, and systolic blood pressure (`SBP`). The results reveal that neck size, SBP, and age are statistically significant predictors of OSA severity, while BMI shows minimal contribution after accounting for multicollinearity with neck size. Diagnostic plots confirm model assumptions of linearity and normality, though the model explains only about 22% of the variability in `ai.` This suggests that other unobserved variables, such as lifestyle or genetic factors, may also influence OSA severity.\n\n## Introduction\n\nObstructive Sleep Apnoea (OSA) is a common sleep disorder characterized by repetitive pauses in breathing due to upper airway obstruction. These interruptions lead to sleep fragmentation, hypoxia, and increased cardiovascular risk. Understanding physiological predictors of OSA severity is essential for developing effective screening and prevention strategies.\n\nIn this study, the arousal index (ai); representing the frequency of awakenings per hour, is used as the dependent variable. Four predictors are considered based on their known associations with OSA:\n\nBody Mass Index (BMI) – a general indicator of body fat.\n\nNeck Size – reflects airway obstruction potential.\n\nSystolic Blood Pressure (SBP) – captures cardiovascular strain.\n\nAge – accounts for physiological changes increasing OSA risk.\n\nThe study provides insights into how physiological and demographic factors correlate with sleep disturbances, helping guide further research and clinical screening in the context of OSA.\n\nMy goal here is to determine which of these variables significantly predict `ai` and to assess the overall performance and appropriateness of the regression model.\n\nFind the data [here.](@https://www.mayoclinic.org/diseases-conditions/sleep-apnea/symptoms-causes/syc-20377631)\n\n## Exploratory Analysis\n\n### Scatter-plot Matrix\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n***Relationships between the response and predictors***\n\n-   `ai` appears to have a moderate positive correlation with sbp, neck_size, and age.\n\n-   bmi and neck_size appear to be highly correlated.\n\nAmong the predictors, **bmi and neck size are highly correlated**, which suggests that multicollinearity could be a concern in regression modeling. This correlation indicates that both variables are related to body composition.\n\n------------------------------------------------------------------------\n\n### Model Fitting and Interpretation\n\nFitting the linear regression model using `ai` as the response variable and the other variables as the predictor.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ai ~ bmi + neck_size + sbp + age, data = sleep)\n\nCoefficients:\n(Intercept)          bmi    neck_size          sbp          age  \n  -0.159406    -0.009852     0.040627     0.010218     0.008789  \n```\n\n\n:::\n:::\n\n\nSignificant predictors (p \\< 0.05) included neck size, sbp, and age, whereas bmi was not statistically significant.\n\n------------------------------------------------------------------------\n\n#### Producing a 95% CI that quantifies the change in ai for each extra cm of neck size:\n\nConfidence Interval at $\\alpha$ = 0.05 or 95%\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n               2.5 %     97.5 %\nneck_size 0.01248892 0.06876571\n```\n\n\n:::\n:::\n\n\nTherefore, for every 1 cm increase in neck size, the arousal index (`ai`) increases by **between 0.012 and 0.068** on the log scale, with **95%** confidence, assuming age and sbp are held constant.\n\nThis provides **strong evidence** that neck size is an important risk factor for obstructive sleep apnoea (OSA) severity, as measured by the frequency of arousal during sleep.\n\n------------------------------------------------------------------------\n\n#### F-test For The Overall Regression\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ai ~ bmi + neck_size + sbp + age, data = sleep)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.67136 -0.32269  0.01491  0.35778  1.47595 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)   \n(Intercept) -0.159406   0.518207  -0.308  0.75893   \nbmi         -0.009852   0.011312  -0.871  0.38557   \nneck_size    0.040627   0.014208   2.859  0.00503 **\nsbp          0.010218   0.003555   2.875  0.00481 **\nage          0.008789   0.002964   2.965  0.00367 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.5417 on 117 degrees of freedom\nMultiple R-squared:  0.2471,\tAdjusted R-squared:  0.2213 \nF-statistic: 9.598 on 4 and 117 DF,  p-value: 9.54e-07\n```\n\n\n:::\n:::\n\n\n`neck_size`, `sbp` and `age` have a significant impact on the response variable, arousal index (`ai`).\n\n------------------------------------------------------------------------\n\n#### Fitting in the Multiple Regression Model\n\n::: {.callout-note appearance=\"simple\" icon=\"false\"}\n$$\nai_i = \\beta_0 + \\beta_1 \\cdot \\text{bmi}_i + \\beta_2 \\cdot \\text{neck\\_size}_i + \\beta_3 \\cdot \\text{sbp}_i + \\beta_4 \\cdot \\text{age}_i + \\varepsilon_i\n$$\n:::\n\n*Model Parameters:*\n\n-   $ai_i$ = arousal index for the *i-th* individual (log scale)\n\n-   $\\beta_0$ = Intercept\n\n-   $\\beta_1$ = bmi\n\n-   $\\beta_2$ = neck_size\n\n-   $\\beta_3$ = sbp\n\n-   $\\beta_4$ = age\n\n-   $\\varepsilon_i$ = random error\n\nThis model aims to assess the overall relationship between the arousal index and the set of physiological predictors: Body Mass Index (bmi), neck size, Systolic Blood Pressure (sbp), and age.\n\n------------------------------------------------------------------------\n\n#### Hypothesis for the Overall ANOVA Test:\n\nThe NULL Hypothesis ($H_0$) states that none of the predictors have an effect on the response variable that is arousal index (ai).\n\n-   $H_0: \\beta_1 = \\beta_2 = \\beta_3 = \\beta_4 = 0$\n\nThe Alternate Hypothesis states ($H_1$) that at least one of the predictors have an effect on the arousal index (ai).\n\n-   $H_1: \\beta_i \\ne 0$\n\n------------------------------------------------------------------------\n\n#### ANOVA Table for the Overall Model\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: ai\n           Df Sum Sq Mean Sq F value    Pr(>F)    \nbmi         1  1.725  1.7250  5.8777 0.0168638 *  \nneck_size   1  3.288  3.2881 11.2040 0.0010982 ** \nsbp         1  3.674  3.6739 12.5185 0.0005789 ***\nage         1  2.580  2.5798  8.7904 0.0036707 ** \nResiduals 117 34.337  0.2935                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n     value      numdf      dendf \n  9.597645   4.000000 117.000000 \n```\n\n\n:::\n:::\n\n\nF-test for this Regression Model: **F = (4,117) and** $p-value < 0.005$\n\nSince the p-value is well below 0.05, we **reject the null hypothesis**. This indicates that at least one of the **predictors is significantly** related to the response variable.\n\n------------------------------------------------------------------------\n\n#### Null Distribution for the test statistic\n\nUnder the null hypothesis ($H_0$), the F-statistic follows an F-distribution with 4 and 117 degrees of freedom.\n\nWhen $H_0: \\beta_1 = \\beta_2 = \\beta_3 = \\beta_4 = 0$, then test statistic is ***F \\~ F(4,117).***\n\n------------------------------------------------------------------------\n\n#### P-value\n\nThe corresponding P-value for this overall regression model is:\n\n$$\\text{p-value} = 9.54 \\times 10^{-7}$$\n\n(or $0.000000954$)\n\nP-value was previously calculated aforementioned above.\n\n------------------------------------------------------------------------\n\n#### Findings\n\n**Statistical Conclusion:**\\\nAs the p-value from the overall F-test is extremely small ($9.54 \\times 10^{-7}$), that is below the significance level ($\\alpha = 0.05$), we reject the null hypothesis that none of the predictors (bmi, neck_size, sbp, age) are related to the response variable.\n\n**Contextual Conclusion:**\\\nThere is strong evidence that at least one of the predictors is significantly associated with the arousal index (`ai`). Thus, this overall regression model as a whole provides quite meaningful explanatory power for predicting `ai`.\n\nIn plain terms, the model isn’t random; there’s a clear relationship between OSA severity and the selected body measurements.\n\n------------------------------------------------------------------------\n\n### Model Validation & Appropriation\n\n*Checking residual vs fitted plots for linearity and constant variance*\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe residuals are generally evenly scattered around the horizontal line at 0, which supports the assumption of linearity. While there is no distinct shape or pattern there is a slight upward curve on the right.\n\nAdditionally, there are a few outliers present, at points 68, 69, and 79; however, they do not demonstrate excessive influence.\n\n*Checking the normality of residuals*\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThe standardized qqplot shows that the residuals mostly follow the normal line, with very slight deviations at the tails. This implies that the **normality assumptions are met**, with no major concerns about non-normality.\n\n::: {.callout-note appearance=\"simple\" icon=\"false\"}\n**Conclusion**: Based on these diagnostic checks, the full multiple regression model appears appropriate for explaining the variability in the arousal index (`ai`).\n:::\n\n------------------------------------------------------------------------\n\n### $R^2$ and It's Significance\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.221317\n```\n\n\n:::\n:::\n\n\nAdjusted $R^2$ = `0.2213`. This is quite a low value, it means that in this model only about 22% of the variability is caused by the predictor variables, the other 78% is due to other factors not included or complete randomness.\\\nThis is not a good model, unreliable, and needs work.\n\n------------------------------------------------------------------------\n\n## Improving the Model\n\n### Checking for predictor significance\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ai ~ bmi + neck_size + sbp + age, data = sleep)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.67136 -0.32269  0.01491  0.35778  1.47595 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)   \n(Intercept) -0.159406   0.518207  -0.308  0.75893   \nbmi         -0.009852   0.011312  -0.871  0.38557   \nneck_size    0.040627   0.014208   2.859  0.00503 **\nsbp          0.010218   0.003555   2.875  0.00481 **\nage          0.008789   0.002964   2.965  0.00367 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.5417 on 117 degrees of freedom\nMultiple R-squared:  0.2471,\tAdjusted R-squared:  0.2213 \nF-statistic: 9.598 on 4 and 117 DF,  p-value: 9.54e-07\n```\n\n\n:::\n:::\n\n\nbmi doesn’t appear significantly impactful on linear model for `ai` and had also displayed strong correlation with neck_size prevoiusly aforementioned above. Therefore, I'll be removing it and re-evaluate necessary assumptions.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ai ~ age + neck_size + sbp, data = sleep)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.65415 -0.35334  0.04008  0.37534  1.45627 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)   \n(Intercept) -0.066166   0.506509  -0.131  0.89629   \nage          0.009007   0.002951   3.053  0.00280 **\nneck_size    0.032630   0.010831   3.013  0.00317 **\nsbp          0.009579   0.003475   2.757  0.00676 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.5412 on 118 degrees of freedom\nMultiple R-squared:  0.2422,\tAdjusted R-squared:  0.2229 \nF-statistic: 12.57 on 3 and 118 DF,  p-value: 3.452e-07\n```\n\n\n:::\n:::\n\n\nVery small increase in the adjusted $R^2$, from 0.221 to 0.222. P-value has dropped and is also still \\<0.05, implying that new model fit has not worsened. All predictors are significant.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nQQnorm is quite linear, no significant deviations.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nResiduals are quite evenly scattered around. No trend or patterns visible.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nResidual vs fitted is also quite normal, no signs of a trend but a slight upwards deviation on the right.\n\nQQplot is relatively linear.\n\nIt would be safe to say that the linearity assumptions are met.\n\nTherefore, final model:\n\n::: {.callout-note appearance=\"simple\" icon=\"false\"}\n$$\nai_i = \\beta_0 + \\beta_1 \\cdot \\text{age} + \\beta_2 \\cdot \\text{sbp} + \\beta_3 \\cdot \\text{neck\\_size} + \\varepsilon\n$$\n:::\n\n------------------------------------------------------------------------\n\n#### Comparing Model Fits\n\n| Model    |   R²   | Adjusted R² | Predictors               | Comment             |\n|:--------------|:-------------:|:-------------:|:--------------|:--------------|\n| Original | 0.2471 |   0.2213    | BMI, Neck Size, SBP, Age | BMI not significant |\n| Refined  | 0.2422 |   0.2229    | Neck Size, SBP, Age      | Slight improvement  |\n\nThe $R^2$ dropped marginally **(from 0.2470586 to 0.2421771)** because we removed a predictor. The adjusted $R^2$ always accounts for the no.of predictors in the model, and only increases if new variables improve the model's efficiency, the increase **(from 0.221317 to 0.2229104**) in adjusted $R^2$ indicates that the new model is likely more accurate . bmi may not have contributed significantly to explaining `ai` in the older model, so its removal results in a more efficient model.\n\n------------------------------------------------------------------------\n\n## Discussion\n\nThe findings confirm that neck size, blood pressure, and age are important factors associated with OSA severity. BMI, although commonly linked to sleep apnoea, was not significant here once neck size was included, suggesting that neck circumference captures the effect of body mass more directly for airway obstruction.\n\nStill, since the model only explains 22% of `ai` variation, other factors such as genetic traits, lifestyle habits, or anatomical structures likely play major roles.\n\n------------------------------------------------------------------------\n\n## Conclusion\n\nThis study shows that neck size, systolic blood pressure, and age are key predictors of OSA severity, measured by the arousal index.\n\nEven though the model explains only a modest portion of the variability, it provides valuable insight into which physical traits are most strongly linked to disrupted sleep. Improving future models with additional lifestyle and physiological data could lead to better prediction and prevention strategies for OSA.\n\n------------------------------------------------------------------------\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}